services:
  # PHP-FPM
  php:
    build: ./php
    container_name: my_project_php
    volumes:
      - ../src:/var/www/html
    environment:
      PUID: ${PUID:-1000}  # UID do seu usuário no host
      PGID: ${PGID:-1000}
    networks:
      - my_project_net

  # Apache
  apache:
    build: ./apache
    container_name: my_project_apache
    ports:
      - "${APACHE_PORT:-8080}:80"
    volumes:
      - ../src:/var/www/html
      - ./apache/myproject.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
    depends_on:
      - php
    networks:
      - my_project_net
    command: ["httpd-foreground"]

  # MariaDB
  mysql:
    image: mariadb:11
    container_name: my_project_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root_password}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-database_name}
      MYSQL_USER: ${MYSQL_USER:-database_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-user_password}
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my_project_net

networks:
  my_project_net:
    driver: bridge

volumes:
  db_data:
